### ISSUE TITLE
Jenkins Configuration as a Code configuration exists?

### ISSUE THREAD

**Issue by gkoloventzos** [jenkinsci/github-autostatus-plugin#109]
Hello,

Is anywhere documented if I can configure this plugin on the Jenkins Configuration as Code?

**Comment by ababushk** [comment]
Well, it isn't documented, so usually I just configure it via the UI and then copy results from 'View configuration' page from CasC plugin. Here's example config from here https://github.com/ababushk/jenkins-observability-talk/blob/main/casc/13-job_and_stage_monitoring.yml
```yaml
unclassified:
  buildStatusConfig:
    dbVersion: 2 # it does NOT mean InfluxDB 2+
    enableGithub: false
    enableHttp: false
    enableInfluxDb: true
    enableStatsd: false
    httpVerifySSL: false
    ignoreSendingTestCoverageToInflux: true
    ignoreSendingTestResultsToInflux: true
    influxDbDatabase: "default"
    influxDbRetentionPolicy: "autogen"
    influxDbUrl: "http://influxdb:8086"
```
